# DATA CLEANING

In [1]:
import numpy as np
import pandas as pd

In [7]:
data = {
    "age":[25,np.nan,30,35,40,1000],
    "salary":[40000,50000,np.nan,70000,80000,9999999],
    "gender":["M","F",np.nan,"M","M","F"]
}

In [19]:
df= pd.DataFrame(data)
# df.head()
df

      age     salary gender
0    25.0    40000.0      M
1     NaN    50000.0      F
2    30.0        NaN    NaN
3    35.0    70000.0      M
4    40.0    80000.0      M
5  1000.0  9999999.0      F

In [4]:
df.isnull().sum()

age       1
salary    1
gender    1
dtype: int64

In [5]:
df.describe()

               age        salary
count     5.000000  5.000000e+00
mean    226.000000  2.048000e+06
std     432.715264  4.445331e+06
min      25.000000  4.000000e+04
25%      30.000000  5.000000e+04
50%      35.000000  7.000000e+04
75%      40.000000  8.000000e+04
max    1000.000000  9.999999e+06

In [9]:
# df=df.dropna()
# df

df["age"]=df["age"].fillna((df["age"].median()))
df["salary"]=df["salary"].fillna((df["salary"]).mean())
df["gender"]=df["gender"].fillna((df["gender"]).mode()[0])
df

      age     salary gender
0    25.0    40000.0      M
1    35.0    50000.0      F
2    30.0  2047999.8      M
3    35.0    70000.0      M
4    40.0    80000.0      M
5  1000.0  9999999.0      F

In [11]:
q1=df["salary"].quantile(0.25)
q3=df["salary"].quantile(0.75)
iqr=q3-q1
iqr

np.float64(1500999.85)

In [20]:
lower = q1 - 1.5 * iqr

upper = q3 + 1.5 * iqr
print(f"lower : {lower}")
print(f"upper: {upper}")

lower : -2196499.7750000004
upper: 3807499.6250000005

In [21]:
outliers = df[
    (df["salary"] < lower)
    |
    (df["salary"] > upper)
]
outliers

      age     salary gender
5  1000.0  9999999.0      F

In [22]:
df=df[(df["salary"]>=lower) & (df["salary"]<=upper)]
df

    age   salary gender
0  25.0  40000.0      M
1   NaN  50000.0      F
3  35.0  70000.0      M
4  40.0  80000.0      M